### ISSUE TITLE
panic when kube context used is for a stopped cluster

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu-labs/educates-training-platform#284]
### Describe the bug

Using educates with local kind cluster, since I have different instances, I start/stop them at will, but sometimes the kube context that is selected in my kubeconfig file points to a cluster that is stopped. In these cases I get a panic on some commands:

```
educates list-workshops
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105b84524]

goroutine 1 [running]:
github.com/vmware-tanzu-labs/educates-training-platform/client-programs/pkg/cmd.(*ClusterWorkshopsListOptions).Run(0x1400004ca60)
	/Users/runner/work/educates-training-platform/educates-training-platform/client-programs/pkg/cmd/cluster_workshop_list_cmd.go:48 +0x194
github.com/vmware-tanzu-labs/educates-training-platform/client-programs/pkg/cmd.(*ProjectInfo).NewClusterWorkshopListCmd.func1(0x140001baf00?, {0x107477900?, 0x4?, 0x105b9e155?})
	/Users/runner/work/educates-training-platform/educates-training-platform/client-programs/pkg/cmd/cluster_workshop_list_cmd.go:109 +0x20
github.com/spf13/cobra.(*Command).execute(0x1400061b800, {0x107477900, 0x0, 0x0})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x1400061a900)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(0x1400004c9c0?)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main()
	/Users/runner/work/educates-training-platform/educates-training-platform/client-programs/cmd/educates/main.go:32 +0xc0
```

How to test:
```
educates create-cluster
# Once is created
docker stop educates-control-plane
# then
educates list-workshops
```

**Comment by jorgemoralespou** [comment]
This is solved in the new installer
